geo_groups = {
    'angola': 'Africa',
    'burkina faso': 'Africa',
    'burundi': 'Africa',
    'benin': 'Africa',
    'botswana': 'Africa',
    'democratic republic of congo': 'Africa',
    'central african republic': 'Africa',
    'congo': 'Africa',
    'cote d\'ivoire': 'Africa',
    'cameroon': 'Africa',
    'cape verde': 'Africa',
    'djibouti': 'Africa',
    'algeria': 'Africa',
    'egypt': 'Africa',
    'western sahara': 'Africa',
    'eritrea': 'Africa',
    'ethiopia': 'Africa',
    'gabon': 'Africa',
    'ghana': 'Africa',
    'gambia': 'Africa',
    'guinea': 'Africa',
    'equatorial guinea': 'Africa',
    'guinea-bissau': 'Africa',
    'kenya': 'Africa',
    'comoros': 'Africa',
    'liberia': 'Africa',
    'lesotho': 'Africa',
    'libyan arab jamahiriya': 'Africa',
    'morocco': 'Africa',
    'madagascar': 'Africa',
    'mali': 'Africa',
    'mauritania': 'Africa',
    'mauritius': 'Africa',
    'malawi': 'Africa',
    'mozambique': 'Africa',
    'namibia': 'Africa',
    'niger': 'Africa',
    'nigeria': 'Africa',
    'reunion': 'Africa',
    'rwanda': 'Africa',
    'seychelles': 'Africa',
    'sudan': 'Africa',
    'st. helena': 'Africa',
    'sierra leone': 'Africa',
    'senegal': 'Africa',
    'somalia': 'Africa',
    'sao tome and principe': 'Africa',
    'swaziland': 'Africa',
    'chad': 'Africa',
    'togo': 'Africa',
    'tunisia': 'Africa',
    'tanzania, united republic of': 'Africa',
    'uganda': 'Africa',
    'mayotte': 'Africa',
    'south africa': 'Africa',
    'zambia': 'Africa',
    'zimbabwe': 'Africa',
    'antarctica': 'Antartica',
    'bouvet island': 'Antartica',
    'south georgia and the south sandwich islands': 'Antartica',
    'heard and mc donald islands': 'Antartica',
    'french southern territories': 'Antartica',
    'united arab emirates': 'Asia',
    'afghanistan': 'Asia',
    # 'armenia': 'Asia',
    # 'azerbaijan': 'Asia',
    'bangladesh': 'Asia',
    'bahrain': 'Asia',
    'brunei darussalam': 'Asia',
    'bhutan': 'Asia',
    'cocos (keeling) islands': 'Asia',
    'china': 'Asia',
    'christmas island': 'Asia',
    # 'cyprus': 'Asia',
    # 'georgia': 'Asia',
    'hong kong': 'Asia',
    'indonesia': 'Asia',
    'israel': 'Asia',
    'india': 'Asia',
    'british indian ocean territory': 'Asia',
    'iraq': 'Asia',
    'iran (islamic republic of)': 'Asia',
    'jordan': 'Asia',
    'japan': 'Asia',
    'kyrgyzstan': 'Asia',
    'cambodia': 'Asia',
    'north korea': 'Asia',
    'korea, republic of': 'Asia',
    'kuwait': 'Asia',
    # 'kazakhstan': 'Asia',
    'lao people\'s democratic republic': 'Asia',
    'lebanon': 'Asia',
    'sri lanka': 'Asia',
    'myanmar': 'Asia',
    'mongolia': 'Asia',
    'macau': 'Asia',
    'maldives': 'Asia',
    'malaysia': 'Asia',
    'nepal': 'Asia',
    'oman': 'Asia',
    'philippines': 'Asia',
    'pakistan': 'Asia',
    'qatar': 'Asia',
    # 'russian federation': 'Asia',
    'saudi arabia': 'Asia',
    'singapore': 'Asia',
    'syrian arab republic': 'Asia',
    'thailand': 'Asia',
    'tajikistan': 'Asia',
    'turkmenistan': 'Asia',
    # 'turkey': 'Asia',
    'taiwan': 'Asia',
    'uzbekistan': 'Asia',
    'viet nam': 'Asia',
    'yemen': 'Asia',
    'andorra': 'Europe',
    'albania': 'Europe',
    'armenia': 'Europe, Asia',  # It's a transcontinental country
    'austria': 'Europe',
    'azerbaijan': 'Europe, Asia',  # It's a transcontinental country
    'bosnia and herzegovina': 'Europe',
    'belgium': 'Europe',
    'bulgaria': 'Europe',
    'belarus': 'Europe',
    'switzerland': 'Europe',
    'cyprus': 'Europe, Asia',  # It's a transcontinental country
    'czech republic': 'Europe',
    'germany': 'Europe',
    'denmark': 'Europe',
    'estonia': 'Europe',
    'spain': 'Europe',
    'finland': 'Europe',
    'faroe islands': 'Europe',
    'france': 'Europe',
    'united kingdom': 'Europe',
    'georgia': 'Europe, Asia',  # It's a transcontinental country
    'gibraltar': 'Europe',
    'greece': 'Europe',
    'croatia': 'Europe',
    'hungary': 'Europe',
    'ireland': 'Europe',
    'iceland': 'Europe',
    'italy': 'Europe',
    'kazakhstan': 'Europe, Asia',  # It's a transcontinental country
    'liechtenstein': 'Europe',
    'lithuania': 'Europe',
    'luxembourg': 'Europe',
    'latvia': 'Europe',
    'monaco': 'Europe',
    'moldova, republic of': 'Europe',
    'macedonia': 'Europe',
    'malta': 'Europe',
    'netherlands': 'Europe',
    'norway': 'Europe',
    'poland': 'Europe',
    'portugal': 'Europe',
    'romania': 'Europe',
    'russian federation': 'Europe, Asia',  # It's a transcontinental country
    'sweden': 'Europe',
    'slovenia': 'Europe',
    'svalbard and jan mayen islands': 'Europe',
    'slovak republic': 'Europe',
    'san marino': 'Europe',
    'turkey': 'Europe, Asia',  # It's a transcontinental country
    'ukraine': 'Europe',
    'vatican city state (holy see)': 'Europe',
    'antigua and barbuda': 'North America',
    'anguilla': 'North America',
    'netherlands antilles': 'North America',
    'aruba': 'North America',
    'barbados': 'North America',
    'bermuda': 'North America',
    'bahamas': 'North America',
    'belize': 'North America',
    'canada': 'North America',
    'costa rica': 'North America',
    'cuba': 'North America',
    'dominica': 'North America',
    'dominican republic': 'North America',
    'grenada': 'North America',
    'greenland': 'North America',
    'guadeloupe': 'North America',
    'guatemala': 'North America',
    'honduras': 'North America',
    'haiti': 'North America',
    'jamaica': 'North America',
    'saint kitts and nevis': 'North America',
    'cayman islands': 'North America',
    'saint lucia': 'North America',
    'martinique': 'North America',
    'montserrat': 'North America',
    'mexico': 'North America',
    'nicaragua': 'North America',
    'panama': 'North America',
    'st. pierre and miquelon': 'North America',
    'puerto rico': 'North America',
    'el salvador': 'North America',
    'turks and caicos islands': 'North America',
    'trinidad and tobago': 'North America',
    'united states minor outlying islands': 'North America, Oceania',  # It's a transcontinental country
    'united states': 'North America',
    'saint vincent and the grenadines': 'North America',
    'virgin islands (british)': 'North America',
    'virgin islands (u.s.)': 'North America',
    'american samoa': 'Oceania',
    'australia': 'Oceania',
    'cook islands': 'Oceania',
    'fiji': 'Oceania',
    'micronesia, federated states of': 'Oceania',
    'guam': 'Oceania',
    'kiribati': 'Oceania',
    'marshall islands': 'Oceania',
    'northern mariana islands': 'Oceania',
    'new caledonia': 'Oceania',
    'norfolk island': 'Oceania',
    'nauru': 'Oceania',
    'niue': 'Oceania',
    'new zealand': 'Oceania',
    'french polynesia': 'Oceania',
    'papua new guinea': 'Oceania',
    'pitcairn': 'Oceania',
    'palau': 'Oceania',
    'solomon islands': 'Oceania',
    'tokelau': 'Oceania',
    'tonga': 'Oceania',
    'tuvalu': 'Oceania',
    # 'united states minor outlying islands': 'Oceania',
    'vanuatu': 'Oceania',
    'wallis and futuna islands': 'Oceania',
    'samoa': 'Oceania',
    'argentina': 'South America',
    'bolivia': 'South America',
    'brazil': 'South America',
    'chile': 'South America',
    'colombia': 'South America',
    'ecuador': 'South America',
    'falkland islands (malvinas)': 'South America',
    'french guiana': 'South America',
    'guyana': 'South America',
    'peru': 'South America',
    'paraguay': 'South America',
    'suriname': 'South America',
    'uruguay': 'South America',
    'venezuela': 'South America',
}